name: Create Module Release

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: Name of the module to release
        type: choice
        options:
          - simple_storage
          - simple_network
        required: true
      release_type:
        description: Type of release (major, minor, patch)
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
      version:
        description: Manually specify version (optional, overrides release_type)
        required: false

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            # Calculate next version without updating package.json
            NEW_VERSION=$(npm version ${{ github.event.inputs.release_type }} --prefix modules/${{ github.event.inputs.module_name }} --no-git-tag-version)
          else
            NEW_VERSION=${{ github.event.inputs.version }}
          fi
          echo "New version: $NEW_VERSION"

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.module_name }}-v$NEW_VERSION
          release_name: ${{ github.event.inputs.module_name }} v$NEW_VERSION
          body: |
            Release notes for ${{ github.event.inputs.module_name }} v$NEW_VERSION

      - run: zip -r ${{ github.event.inputs.module_name }}-v$NEW_VERSION.zip modules/${{ github.event.inputs.module_name }}
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}  # <-- Added upload_url
          asset_path: ${{ github.event.inputs.module_name }}-v$NEW_VERSION.zip
          asset_name: ${{ github.event.inputs.module_name }}-v$NEW_VERSION.zip
          asset_content_type: application/zip
