name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Type of release (major, minor, patch)
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
      release_note:
        description: Enter the release note.
        required: true
      version:
        description: Manually specify version (optional, overrides release_type)
        required: false

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      id: release
      step: set_release_variables

    steps:
      - uses: actions/checkout@v3

      - name: Set Release Variables
        id: set_release_variables
        run: |
          # Check for manual version input and update package.json if necessary
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            CURRENT_VERSION=$(jq -r .version package.json)
            if [[ "$CURRENT_VERSION" < "${{ github.event.inputs.version }}" ]]; then
              npm version "${{ github.event.inputs.version }}" --no-git-tag-version
            else
              echo "::error::Input version (${GITHUB_EVENT_INPUTS_VERSION}) is less than or equal to current version ($CURRENT_VERSION). Release aborted."
              exit 1
            fi
            NEW_VERSION="${{ github.event.inputs.version }}"
          else
            # Calculate next version in the root package.json
            NEW_VERSION=$(npm version ${{ github.event.inputs.release_type }} --no-git-tag-version)
          fi
          echo "::set-output name=new_version::${NEW_VERSION}"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.set_release_variables.outputs.new_version }}"
          release_name: "${{ steps.set_release_variables.outputs.new_version }}"
          body: |
            Release note for ${{ steps.set_release_variables.outputs.new_version }} : ${{ github.event.inputs.release_note }}

