name: Release please workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - modules/**

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Updated to latest version

      - name: Get latest release
        uses: actions/github-script@v7  # Updated to latest version
        with:
          script: |
            async function getLatestRelease() {
              try {
                const { owner, repo } = context.repo;
                const latestRelease = await github.rest.repos.getLatestRelease({ owner, repo });
                console.log("Latest release:", latestRelease.data);

                // Do something with the release data
              } catch (error) {
                console.error("Error fetching latest release:", error);
              }
            }

            getLatestRelease();
