name: Create Module Release

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: Name of the module to release
        type: choice
        options:
          - simple_storage
          - simple_network
        required: true
      release_type:
        description: Type of release (major, minor, patch)
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
      version:
        description: Manually specify version (optional, overrides release_type)
        required: false

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check for jq
        if: !which jq
        run: sudo apt-get install jq -y
      - uses: actions/checkout@v3
      - run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            npm version ${{ github.event.inputs.release_type }} --prefix modules/${{ github.event.inputs.module_name }}
          else
            npm version ${{ github.event.inputs.version }} --prefix modules/${{ github.event.inputs.module_name }}
          fi
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: 16  # Specify Node.js version 16
          tag_name: ${{ github.event.inputs.module_name }}-v$(cat modules/${{ github.event.inputs.module_name }}/package.json | jq -r .version)
          release_name: ${{ github.event.inputs.module_name }} v$(cat modules/${{ github.event.inputs.module_name }}/package.json | jq -r .version)
          body: |
            Release notes for ${{ github.event.inputs.module_name }} v$(cat modules/${{ github.event.inputs.module_name }}/package.json | jq -r .version)
      - run: zip -r ${{ github.event.inputs.module_name }}-v$(cat modules/${{ github.event.inputs.module_name }}/package.json | jq -r .version).zip modules/${{ github.event.inputs.module_name }}
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.event.inputs.module_name }}-v$(cat modules/${{ github.event.inputs.module_name }}/package.json | jq -r .version).zip
          asset_name: ${{ github.event.inputs.module_name }}-v$(cat modules/${{ github.event.inputs.module_name }}/package.json | jq -r .version).zip
          asset_content_type: application/zip
